### ISSUE TITLE
ñ as {~n}

### ISSUE THREAD

**Issue by johanneswilm** [fiduswriter/biblatex-csl-converter#124]
Hey @retorquere ,
one of the test entries you provided looks like this:

```
@article{blom1999diffuse,
    title={Diffuse gamma-ray emission from starburst galaxies and M31},
    author={Blom, J.J. and Paglione, T.A.D. and Carrami{~n}ana, A.},
    journal={The Astrophysical Journal},
    volume={516},
    pages={744},
    year={1999},
    publisher={IOP Publishing}
  }
```

Note that the ñ is written as `{~n}` (no backslash). This is currently not accepted. Should it be accepted?

**Comment by johanneswilm** [comment]
Also This line does not give the correct last name:

```
author={Smol{{c}}i{'c}, V and Schinnerer, E and Zamorani, G and Bell, EF and Bondi, M and Carilli, CL and Ciliegi, P and Mobasher, B and Paglione, T and Scodeggio, M and others},
```

The first last name should be `Smolčić`. Is this simply a case of incorrectly formatted BibTeX?

**Comment by retorquere** [comment]
I can't find either of those in my test suite, but:

> author={Blom, J.J. and Paglione, T.A.D. and Carrami{~n}ana, A.},

is valid TeX, even though the person that wrote it surely would have meant `{\~n}`. But yes, it is perfectly acceptable TeX, `~` is a non-breaking space, and so it should be accepted as valid input.

> author={Smol{�{c}}i{'c}, V 

you can sort of see the intent here, but I don't think any parser should infer `Smolčić` from it because that clearly does not align with the almost-valid TeX here; I don't know how TeX would parse the unicode replacement character, but all the rest is straightforward TeX.

**Comment by retorquere** [comment]
The directory structure does suggest they cam from me, but that would also indicate I received them as a live sample from someone at some point; all samples in `test/fixtures/import` are from the wild.

**Comment by johanneswilm** [comment]
Ok, yes `Carrami{~n}ana` is valid TeX and we do accept it. But we read it
as "Carrami nana" whereas the author surely meant "Carramiñana". Under any
TeX rule, is there a reason we should read it as "Carramiñana"?

**Comment by retorquere** [comment]
I wouldn't advice it.
