### ISSUE TITLE
Date ranges?

### ISSUE THREAD

**Issue by retorquere** [fiduswriter/biblatex-csl-converter#13]
I have an entry that has `Year = {1982--1983}`. What to do with these?

**Comment by johanneswilm** [comment]
The parser does date ranges. However it expects this format:

```YYYY-mm-dd/YYYY-mm-dd```

and it only accept it on the fields that are registered as date fields. I believe it also allows a few other options for the delimiter between year, month and day, and it allows to leave out the month or day. We can of course add to that. But where is the Year-field defined like that? If it's not part of hte bibtex definition, and not a common output from some app that is being used a lot, I think I would instead tell the users to fix their entry.

What do you think?

**Comment by retorquere** [comment]
I think you're right in general terms -- but I cannot in fact tell my users to fix their entry, as I cannot tell them anything. Just "an error has occurred", which is why I've previously been incredibly liberal. In my case, I don't even do date validation in the parser beyond assembling them if they are separate year/month/day fields. If I find a `date`, I just stuff that into Zotero as I find it. I do date handling on output (which I must in any case, because not all entries come into Zotero through my own import).

**Comment by johanneswilm** [comment]
I agree with trying to be very liberal. But there are limitations when it starts being unclear what is meant. What do you do if someone writes something like:

```
Month = {1983-1986-1992}
date = {1992-18-16}
```
etc. . To keep it all maintainable, I think we need to make sure to not get users used to writing any kind of nonsense because eventually it will break. As a Zotero user who almost always imports via bibtex-from-clipboard import, it seems like the non-existent bug reports is something that Zotero must fix anyway.

But what we can do if there is no specification that defines these fields well, is that we write our own document for these extra fields and try to get at least some consistency in what we accept and what we don't. That way we can be a bit more creative, while not ending up with spaghetti-code that noone can maintain if both of us get hit by a bus.

**Comment by retorquere** [comment]
I also get dates however like what's below, and biblatex merrily compiles that -- see the biblatex manual, section 2.3.8. `Year = {1982--1983}` is undesirable even according to the manual, but it is within spec.

```
\documentclass{article}
\usepackage[
    backend=biber,
    natbib=true,
    url=false, 
    doi=true,
    eprint=false
]{biblatex}

\usepackage{filecontents}

\begin{filecontents}{refs1.bib}
@String{pub-FRED = "Freds Publishing"}
@String{pub-FRED:adr = "London, UK"}
\end{filecontents}

\begin{filecontents}{refs2.bib}


@Book{cit1,
  author = {R. A. Bert},
  year = {8 juin 2017},
  title = {{{Atlantic}} bluefin tuna ({ \emph{Thunnus thynnus}})},
  publisher = pub-FRED,
  address = pub-FRED:adr
}

\end{filecontents}

\addbibresource{refs1.bib}
\addbibresource{refs2.bib}

\begin{document}

\cite{cit1}

\printbibliography

\end{document}
```

**Comment by retorquere** [comment]
This does not go for `month` and `date` under biblatex, only `year` BTW.

**Comment by johanneswilm** [comment]
2.3..8 read

```
If there is no date field in an entry, biblatex will also consider the fields year and month
for backwards compatibility with traditional BibTeX but this is not encouraged as
explicit year and month are not parsed for date meta-information markers or
times and are used as-is. 
```

If I read that correctly, it means the string of that field is put wherever a date is needed, and it is not parsed. The question then is if we can come up with something that parses these fields sufficiently to cover most common usecases. Taken the ```[1976]``` and putting it into origdate should be not be so difficult. But is that as difficult as it gets?

I think I would be interested in going through reasonable efforts to make usecases of `year` work. But if it turns out to be impossible, I'd also be OK with dropping it and just providing access to it through the raw fields or so.

**Comment by retorquere** [comment]
The date parser I use is fairly complex (and messy) as the dates I get in are complex (and messy), not sure you'd want to go there, and it leans in part on the citeproc date parser. But putting what's in the year field in a raw field is only half the issue for me -- I need the parsed string with latex constructs converted to unicode & markup. I'd prefer not to have `year = {[2014]}` moved to a field like `origdate` unless I can reconstruct, because Zotero doesn't have any field to put it -- except the `date` field.

**Comment by johanneswilm** [comment]
Are you saying you need textbf, etc. in the year field?

The tex char replacement is now performed for the entire input string before parsing. That sped up import by about a factor 10. It also means that the raw fields have those applied. What they don't have is the style parser, but none of tge date fields go through that. Do you need an option to enable style parsing of the year?

**Comment by retorquere** [comment]
Style parsing of the year: hard to tell, leaning towards "yes". The spec allows any LaTeX to be there, so something like `3<sup>rd</sup> century` is allowed.

**Comment by johanneswilm** [comment]
Making the year field available as an "unknown" field that is styled like a literal field is not that difficult. I can give you that. Same for month.

**Comment by retorquere** [comment]
That'd work for me.
