### ISSUE TITLE
BibLaTeX output

### ISSUE THREAD

**Issue by retorquere** [fiduswriter/biblatex-csl-converter#31]
I'm not entirely sure yet whether I'll also use biblatex-csl-converter for BibLaTeX output (see below), but is biblatex-csl-converter going to allow encoding unicode as latex constructs, or will it just trust biblatex to handle unicode? 

The reasons why I might stick with my own Bib*La*TeX production:

* I need to do BibTeX in addition to BibLaTeX
* For BibTeX I need to be able to re-code unicode characters into LaTeX constructs
* I'd have to convert Zotero to bibDB, might as well just produce biblatex at that point.

**Comment by retorquere** [comment]
(I have to admit that I usually have BBT produce even biblatex output with commands instead of unicode characters. I just find it prettier).

**Comment by johanneswilm** [comment]
Well, in general our philosophy has been something along the lines of "the world of latex/bibtex is an incompatible mess, so we'll only provide the users with output that relies on a narrowly defined subset of packages and uses the latest version of available technology".

That being said, I have my doubts we can push end users to rely on TexLive 2016 or maybe even Tex Live beta 2017 to get name support for biblatex. So for that we probably need both with a config option.

As for BBT, I can see how it can be problematic. If the character replacement is the main issue, we can try to set it up so that one can choose whether to do full replacement or only what is really needed.

> (I have to admit that I usually have BBT produce even biblatex output with commands instead of unicode characters. I just find it prettier).

Right, from a geek-perspective I can see how that can make sense. But for the average FW user, who likely doesn't know code at all (which is why they came to FW in the first place), this doesn't seem very useful. So if we add this, we shouldn't force it on users.

Whether you decide to switch to this package or not can also be something you decide later on. I think the json format we are producing here should be fairly easy to handle to create other output formats as well. If there are more differences, it may even make sense to create a fork of the biblatex exporter and make it produce bibtex to be consumed by natbib or whatever people use for non-biblatex bib these days.

**Comment by retorquere** [comment]
For full replacement you need to know what characters are only available in math mode.

**Comment by johanneswilm** [comment]
ok, so one would need to step through the entire document and replace for individual parts based on whether or not one is in math mode? 

I guess you could do that, but I can also see that this may be too much to bother with.

**Comment by retorquere** [comment]
I don'tthink it's going to be useful to the FidusWriter case, no. It's a necessity for me, but I already have the code that does this.

**Comment by johanneswilm** [comment]
Ok, but then as long as we make sure this can be done some time in the future, you'll just stay with your existing exporter.

**Comment by johanneswilm** [comment]
Look at this. This is how the other fork used to have latex support https://github.com/ORCID/bibtexParseJs/commit/478a356baacac332c2c8dce147f36e93e802eae4

**Comment by retorquere** [comment]
That looks a lot like how my parser did it.
