### ISSUE TITLE
percentage sign in bibfields

### ISSUE THREAD

**Issue by johanneswilm** [fiduswriter/biblatex-csl-converter#46]
I guess traditionally the percentage sign means in latex that only comments follow in that line. The parser also assumes that, whcih is why it's having problems with

```
SLACcitation   = "%%CITATION = ARXIV:1403.3399;%%"
```

Should this be accepted, @retorquere ?

**Comment by retorquere** [comment]
biber accepts %-comments outside fields, so something like

```
@article{citekey,
    author = {Heyns, Emiliano}, %The author
    % lengthy explanation of the title
    title = {Short title here},
}
```

is accepted. But the % sign inside a field value breaks reference parsing: 

```
@article{citekey,
    author = {Heyns, Emiliano}, %The author
    % lengthy explanation of the title
    title = {%%
      Short title here},
}
```

breaks biber parsing. `%` isn't even interpreted as "ignore until end of line", biber just keels over.

My own parser currently treats `%` as if it were `\%` because I was once handed a testcase that had a `%`. This may have been a bibtex testcase although I can't imagine bibtex doing better with the `%` in the reference. I have no strong preference one way or the other between:

1. treat it as `\%`
2. treat it as a LaTeX comment, so ignore everything until the first newline you find
3. treat it as an error and abort parsing that reference

I'd say do whatever's easiest.

**Comment by johanneswilm** [comment]
For now I have only changed things so that the parser doesn't hang on any of the tests
