### ISSUE TITLE
BibLatexParser output has no "length" field

### ISSUE THREAD

**Issue by retorquere** [fiduswriter/biblatex-csl-converter#5]
The references are returned in `.output` as an object with string-formatted numeric keys (`'0'` rather than `0`), and the output object doesn't have a `length` field, so I have to loop through the object until I find an `undefined` to know I've had them all.

**Comment by johanneswilm** [comment]
But you have Object.keys(output).length right? How would you want to add the length? By adding it to the prototype of the object? That's often not really recommended.

> an object with string-formatted numeric keys ('0' rather than 0)

This is something that JavaScript does itself, when you use numeric keys, right? I can still get the entries using output[3], etc. .

**Comment by retorquere** [comment]
I didn't have `Object.keys(output).length`, no. I managed to obliterate my test script so I have to reconstruct it, but I basically had something like

```
function length(output) {
  var l = 0
  while (output[l]) { l++ }
  return l
}
```

Yes, if you do `a = {}; a[3] = true` you get `{'3': true}`. `a[3]` will still work. But in such a case, `length` needs to be set manually on the result object.

**Comment by johanneswilm** [comment]
I am confused. What are you asking for exactly?

Do you want this?
```
output = {'0':{...},'1':{...},...,'length': X}
```

The problem with that is that if you iterate over ```Object.keys(output)```, one of the keys will be "length" and will most likely crash whatever you are planning on.  Also `Object.keys(output).length` will be one too high.

I guess the alternative would be to somehow add the length to the prototype of the object so that it is available, but isn't counted in terms of length, and isn't one of the keys either. But messing aroudn with the prototype of objects is usually not seen as such a good idea.

**Comment by retorquere** [comment]
Yes, that would be my preference. 

It is [possible to exclude properties from enumeration](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Object/defineProperty) (see `enumerable`), but why not just use an array rather than a pseudo-array?

**Comment by johanneswilm** [comment]
Well, the ids just happens to start from 0. When you export to biblatex/csl, it will let you decide which ids you want to export. The ids in the output csl json will be the same, which you'll need if you export all entries ofone document.

And for example in FW, the entries will have ids that come from the database. They will very seldom be 0, 1, 2... . More likely is 346589, 2345643, 3421, etc. .

Given that Object.keys() now is available, I don't think one usually also adds this info to the object. What would the advantage be?

**Comment by retorquere** [comment]
Oh, they're actually IDs, not indexes? Why numeric then? BibTeX entries will have actual IDs, no?

**Comment by retorquere** [comment]
I was still thinking about this as an import format. You intend to use it in more places.

**Comment by johanneswilm** [comment]
Well, most databases are based on numeric pk values. It also imports the key from the biblatex file. But if users generate entries through the UI, this will be autogenerated, and it's only unique per user, not per server...

I actually first created an array. You can still get the array at parser.entries after getting the output. But I wanted to use the format for output of the importer and input of the exporters. That's why I switched.

**Comment by retorquere** [comment]
Yeah, no issue. I wasn't thinking about your further use of the format. I will only use it as a step in transformating them to Zotero references, for Zotero -> Bib(La)TeX I have a different format.

**Comment by johanneswilm** [comment]
Ok. Of course I want to make sure it also works for your usecase. If you have Object.keys().length, is that good enough?

**Comment by retorquere** [comment]
That's good enough.

**Comment by johanneswilm** [comment]
Great!
