### ISSUE TITLE
question: marks on text

### ISSUE THREAD

**Issue by retorquere** [fiduswriter/biblatex-csl-converter#54]
Are marks always of the form 

```
marks: [ { type: 'sup'}, { type: 'nocase'} ]
```

or can they have more info than the type? If not, would

```
marks: { sup: true, nocase: true }
```

not be simpler?

**Comment by johanneswilm** [comment]
I guess our current marks only have this one piece of information. If we had something like headline styling, that would have at least two attributes (headline level and the type). But we are now kind of married to this data format given that since last winter it has been incorporated into all parts of Fidus Writer. So at least for us it would not be convenient at all to change anything about it at this stage.

**Comment by johanneswilm** [comment]
Also, we have quite a number of production users at various institutions and we would have to create and test conversion scripts for all of their data...

**Comment by retorquere** [comment]
Don't bother then; a one-liner will do it anyhow for me:

```
marks = (node.marks || []).reduce((function(acc, mark) { acc[mark.type] = true; return acc; }), {});
```

what can I expect in `marks`? I have seen `nocase` and `sup`, I expect to see `sub` pop up as I work through my test cases, anything else?

**Comment by johanneswilm** [comment]
Just copying from our UI: Strong, Emphasis, Small caps, Subscript, Supscript, Case Protect. So basically these should be all the marks supported by CSL. And the idea was that we could expanding without changing the syntax, should CSL ever expand what it supports, even with extra attributes..

**Comment by retorquere** [comment]
And these would then be type `strong`, `emphasis`, `smallcaps`, `sub`, `sub` and `nocase`, respectively?

**Comment by johanneswilm** [comment]
that sounds correct, yes. But your guess is as good as mine. I would have to look into the sources as well.

**Comment by retorquere** [comment]
Ah, I see them now, its

* strong
* em
* smallcaps
* enquote
* sub
* sub
* nocase
