### ISSUE TITLE
\textbackslash interpreted as \ in the parse phase?

### ISSUE THREAD

**Issue by retorquere** [fiduswriter/biblatex-csl-converter#76]
```
@article{ck1,
  title = {\textbackslash\textbackslash\{\}: \\{}}
}
```

parses to 
```
{
  "references": {
    "1": {
      "bib_type": "article",
      "entry_key": "ck1",
      "fields": {
        "title": [
          {
            "type": "text",
            "text": "\n{}: \n"
          }
        ]
      }
    }
  },
  "errors": [],
  "warnings": []
}
```

but I had expected `\\{}: \n`

**Comment by johanneswilm** [comment]
The issue is this:
`\textbackslash`-replacement <-- should be applied to the entire document
`\\`-replacement <-- should only happen to the literal field and not, for example, verbatim-fields.

We earlier tried putting the regexp replacement into the handling of individual fields. The result was that it took forever and it wasn't a workable solution. I think you were actually the bug reporter on that. What we obtained was a speed optimization of about a factor 100 or 1000 or something like that, but the negative aspect is that it is possible to create data that will break the parser if one aims to break it.

So yes, we could make an exception for this one command. But we cannot make exceptions for all commands. So I would argue that if we do it, it has to be because this is based on actual user data where this error showed up, not because it could theoretically show up.

**Comment by retorquere** [comment]
Alright, I've disabled that test case in my suite.

**Comment by johanneswilm** [comment]
But it was a gest case from a real user? I mean we can do it...

**Comment by retorquere** [comment]
No, this must have been a synthetic case.

**Comment by johanneswilm** [comment]
@retorquere - in this branch I have tried to come up with a solution: It first replaces the backslashes with unused unicode character `\u0871` and then later replaces that character with a real backslash when parsing the literal. This seems to fix some of your tests. However -- this would create a new issue for fields that are not read as literals. If someone puts a `\backslash` command in a verbatim field or a date field, it will still be there in the final output. This si the second unused character we use, so just to make sure none of these ever spill out into the wild, I clean up the output at the very end.

**Comment by retorquere** [comment]
I do agree BTW that we shouldn't get too hung up on synthetic tests.
