### ISSUE TITLE
Jabref changed their groups format again

### ISSUE THREAD

**Issue by retorquere** [fiduswriter/biblatex-csl-converter#84]
Fortunately this time it may only require recognizing `jabref-meta: grouping` (JR 4.1) as equivalent to `jabref-meta: groupstree` (JR4.0)

There's also a new `@Comment{jabref-meta: fileDirectory:.;}` which probably means the attachments can live elsewhere. It'd be nice to have that too if possible.

**Comment by johanneswilm** [comment]
Ok. I am on holidays until mid February, but feel free to write a patch in the meantime.

**Comment by retorquere** [comment]
How do I cut a release?

Why JabRef doesn't just adopt JSON is beyond me. I think I have it down, but I had to add a local workaround in the groups parsing for `groups    = {middle_ear_interspecies},` being parsed into

```
[
  {
    "type": "text",
    "text": "middle"
  },
  {
    "type": "text",
    "text": "e",
    "marks": [
      {
        "type": "sub"
      }
    ]
  },
  {
    "type": "text",
    "text": "ar"
  },
  {
    "type": "text",
    "text": "i",
    "marks": [
      {
        "type": "sub"
      }
    ]
  },
  {
    "type": "text",
    "text": "nterspecies"
  }
]
```

**Comment by johanneswilm** [comment]
To make a release: npm version major/minor/patch. Then push to the master
branch including the git tag. It should do everything else automatically
then.

On 10 Jan 2018 9:27 pm, "Emiliano Heyns" <notifications@github.com> wrote:

How do I cut a release?

Why JabRef doesn't just adopt JSON is beyond me. I think I have it down,
but I had to add a local workaround in the groups parsing for groups =
{middle_ear_interspecies}, being parsed into

[
  {
    "type": "text",
    "text": "middle"
  },
  {
    "type": "text",
    "text": "e",
    "marks": [
      {
        "type": "sub"
      }
    ]
  },
  {
    "type": "text",
    "text": "ar"
  },
  {
    "type": "text",
    "text": "i",
    "marks": [
      {
        "type": "sub"
      }
    ]
  },
  {
    "type": "text",
    "text": "nterspecies"
  }
]

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/fiduswriter/biblatex-csl-converter/issues/84#issuecomment-356710008>,
or mute the thread

**Comment by retorquere** [comment]
It says in Travis:

> Skipping a deployment with the npm provider because this is not a tagged commit

Should I change the tag to an annotated tag? That's what I have to do for Circle too.

**Comment by johanneswilm** [comment]
I was also confused by this yesterday. It turns out it makes two builds: one for the tag and one for the commit. The one for the tag pushes to npmjs. 

But also, you need to make sure to push the tag to github. This does not happen by itself! You can do it manually with a command such as ```git push --tags``` and there is also a way to make it happen every time you do ```git push```, but I forgot ho to set that up. Google is your friend! :)

**Comment by johanneswilm** [comment]
This shows that the tag was not pushed: https://github.com/fiduswriter/biblatex-csl-converter/releases

**Comment by retorquere** [comment]
OK, so:

1. npm version patch
2. git push --tags

yeah?

**Comment by johanneswilm** [comment]
I think so. I have it set up to automatically push tags with just ```git push```. But I forgot how I set it up to do that.

**Comment by retorquere** [comment]
I have this in my `package.json` BTW:

```
"postversion": "TAG=$(echo $(git describe --tags $(git rev-list --tags --max-count=1))) && git tag -a $TAG $TAG -f -m \"$(git log `git describe --tags --abbrev=0 HEAD^`..HEAD --oneline)\" && git push && git push --tags",
```

which just pushes an annotated tag directly after the `npm version` is ran.

**Comment by retorquere** [comment]
Nope, that two-step doesn't do it.

**Comment by johanneswilm** [comment]
Now you pushed the tags at least https://github.com/fiduswriter/biblatex-csl-converter/releases

And 1.3.4 was released to npmjs: https://www.npmjs.com/package/biblatex-csl-converter

**Comment by johanneswilm** [comment]
Also 1.3.5: https://www.npmjs.com/package/biblatex-csl-converter

So yes, it worked.

The way to always push tags is apparently:

git push --follow-tags

**Comment by retorquere** [comment]
Cool -- that should fix it then. I've added a reminder to run `git push --follow-tags` in the `postversion`.
