### ISSUE TITLE
Preserve entry key during BibTex to CSL conversion

### ISSUE THREAD

**Issue by hubgit** [fiduswriter/biblatex-csl-converter#98]
When converting from BibTeX to CSL JSON, the intermediate JSON has an `entry_key` property which contains the key of the item from the original BibTeX file.  However, the item in the CSL output only has a number as its `id` property. It would be useful if the keys could be retained through the conversion and used as the ids of the output CSL JSON items.

**Comment by retorquere** [comment]
@johanneswilm would need to comment on the repercussions for his use, but one potential problem could be that the parser will dutifully parse bibtex files that have non-unique keys.

**Comment by johanneswilm** [comment]
I checked how Fidus Writer uses it. We don't use the original key for anything, and we do use the number ID. However, we only convert entries one by one from the intermediate JSON to CSL, so it would not be difficult to switch to what you are proposing here.

But it does introduce the issue @retorquere mentioned and that's basically why we didn't use those as keys. Also, I believe we might have cases where the original citation doesn't have any key at all. And it's not exactly simplifying things that the CSL uses keys that are different from the keys used in the intermediate JSON. So hmm, not sure. Maybe using a switch would be a good idea. There is no CSL field that could be used to "annotate" the citation with the original key, is there?

**Comment by retorquere** [comment]
It is true that (out of spec) bibtex files exists that don't have a citekey (I think EndNote once exported bibtex that way), but that could be handled by `this.cslDB[bibId].id = this.bibDB[bibId].entry_key || bibId`.

I don't have strong opinions on the matter since I only use the bibtex-parsing part of the lib, not the csl-producing part, but there is [no formal field in CSL](http://docs.citationstyles.org/en/stable/specification.html#appendix-iv-variables) intended to hold something like a citekey. I'm not sure what the `.id` field does for fiduswriter, but if that's produced in the CSL output, given that there's already a superset of the formal fields in the output, we might as well add a `citation-key` field rather than replacing the `id` field.

**Comment by retorquere** [comment]
(sidenote: I do produce CSL, and in that CSL, I do put the citekey in the `id` field, because it's intended for use with pandoc. But that CSL is produced largely by Zotero, just decorated by me)

**Comment by johanneswilm** [comment]
Using the same ID in the intermediate JSON and the citeproc one is needed by FW in order to be able to update the right items, etc. . It's only one line of code to overwrite the IDs in the output of the converter, but it does have the above-mentioned issues.

@hubgit could it be a solution to add this entry key under a different name than 'id'? Then we avoid the issues of using different systems of IDs for intermediate JSOn and CSL JSON, entries with empty string keys and you can be really sure that the field contains a field that was in the original source and is not just an ID we autogenerated later. Alternatively, I suggest we make an option that can be turned on and off.

**Comment by johanneswilm** [comment]
To explain how we use it: We import bibtex/biblatex data. Then we store it in the intermediate JSON and we also let users edit it (the format is prosemirror-compatible). Users can even create completely new entries that were not ever bibtex. When exporting, we use CSL for everything web-related and biblatex for latex output. In the case of the biblatex output, we try to use original keys when the data was first imported. But if the entry was created by a user in our editor, if it had an empty string id to start with or if ids are duplicate in the final output, we use a generated id instead. In the case of CSl, we never saw the use for the original entry key, but I can see how that can be useful for other usecases.

**Comment by hubgit** [comment]
I'd seen a few examples of CSL JSON using `id` for the "citation key" and assumed that's how everyone uses it, but the more I look into it the more examples I've found of this identifier being stored in other places, so there obviously isn't a definitive answer. I'm going to close this issue to try a different approach - thanks for the considered reasoning.
